name: "Set up env vars"
description: "Set up env vars"
inputs:
  tag:
    required: false
    type: string

runs:
  using: "composite"
  steps:
    - name: Set env
      env:
        HEAD_TAG: ${{ inputs.tag || github.event.pull_request.head.sha || github.sha }}
      shell: bash
      run: >-
        echo "TAG=${HEAD_TAG::8}" >> ${GITHUB_ENV};
        echo ${HEAD_TAG::8}
    - name: Downcase repo
      env:
        REPO: "${{ github.repository }}"
      shell: bash
      run: |
        echo "REPO_LOWER=${REPO,,}" >> ${GITHUB_ENV}
    - name: Make sure docker-compose is installed
      shell: bash
      run: |
        if [[ ! -f $DOCKER_CONFIG/cli-plugins/docker-compose ]]; then
          DOCKER_CONFIG=${DOCKER_CONFIG:-$HOME/.docker};
          mkdir -p $DOCKER_CONFIG/cli-plugins;
          curl -SL https://github.com/docker/compose/releases/download/v2.12.2/docker-compose-linux-x86_64 -o $DOCKER_CONFIG/cli-plugins/docker-compose ;
          sudo ls -la $DOCKER_CONFIG/cli-plugins
        else
          echo "$DOCKER_CONFIG/cli-plugins/docker-compose is already installed and given the below permisisons:"
          sudo ls -la $DOCKER_CONFIG/cli-plugins
        fi

