name: "Set up env vars"
description: "Set up env vars"
inputs:
  tag:
    required: false
    type: string

runs:
  using: "composite"
  steps:
    - name: Set env
      env:
        HEAD_TAG: ${{ inputs.tag || github.event.pull_request.head.sha || github.sha }}
      shell: bash
      run: >-
        echo "TAG=${HEAD_TAG::8}" >> ${GITHUB_ENV};
        echo ${HEAD_TAG::8}
    - name: Downcase repo
      env:
        REPO: "${{ github.repository }}"
      shell: bash
      run: |
        echo "REPO_LOWER=${REPO,,}" >> ${GITHUB_ENV}
    - name: Make sure docker-compose is installed
      shell: bash
      run: |
        if [[ ! -f /usr/libexec/docker/cli-plugins/docker-compose ]]; then
          mkdir /usr/libexec/docker/cli-plugins;
          curl -L "https://github.com/docker/compose/releases/download/v2.6.0/docker-compose-Linux-x86_64" -o /usr/libexec/docker/cli-plugins/docker-compose ;
          chmod +x /usr/libexec/docker/cli-plugins/docker-compose;
          sudo ls -la /usr/libexec/docker/cli-plugins
        else
          echo "docker-compose is already installed"
        fi
