name: "Set up env vars"
description: "Set up env vars"
inputs:
  tag:
    required: false
    type: string

runs:
  using: "composite"
  steps:
    - name: Set env
      env:
        HEAD_TAG: ${{ inputs.tag || github.event.pull_request.head.sha || github.sha }}
      shell: bash
      run: >-
        echo "TAG=${HEAD_TAG::8}" >> ${GITHUB_ENV};
        echo ${HEAD_TAG::8}
    - name: Downcase repo
      env:
        REPO: "${{ github.repository }}"
      shell: bash
      run: |
        echo "REPO_LOWER=${REPO,,}" >> ${GITHUB_ENV}
    - name: Make sure docker-compose is installed
      shell: bash
      run: |
        if [[ ! -f /home/runner/bin/docker-compose ]]
        then
          echo "The file docker-compose file does not exist yet!"
          mkdir /home/runner/bin
          curl -L "https://github.com/docker/compose/releases/download/v2.6.0/docker-compose-Linux-x86_64" -o /home/runner/bin/docker-compose
          chmod +x /home/runner/bin/docker-compose
        fi
