name: "Build Docker Images"
on:
  workflow_dispatch:
    inputs:
      platforms:
        default: "linux/amd64,linux/arm64"
        type: string
      solr:
        description: "Use if you need to build a specific Solr image and push to the registry"
        required: false
        type: boolean
      tag:
        required: false
        type: string
      target:
        required: false
        type: string
      worker:
        required: false
        type: boolean
      workerTarget:
        required: false
        type: string
  workflow_call:
    inputs:
      platforms:
        default: "linux/amd64,linux/arm64"
        type: string
      solr:
        required: false
        type: boolean
      tag:
        required: false
        type: string
      target:
        required: false
        type: string
      worker:
        required: false
        type: boolean
      workerTarget:
        required: false
        type: string

env:
  REGISTRY: ghcr.io

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Context for Buildx
        run: docker context create builders
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        with:
          version: latest
          endpoint: builders
      - id: setup
        name: Setup
        uses: scientist-softserv/actions/setup-env@self-hosted-runner
        with:
          tag: ${{ inputs.tag }}
      - name: Retag action for web
        uses: docker/metadata-action@v4.1.1
        with:
          images: |
            name=${{ env.REGISTRY }}/${{ env.REPO_LOWER }}
          tags: |
            type=raw,value=latest,enable={{is_default_branch}}
            type=sha,value=latest,enable={{is_default_branch}}
          flavor: |
            latest=auto
      - name: Retag action for worker
        if: ${{ inputs.worker }}
        uses: docker/metadata-action@v4.1.1
        with:
          images: |
            name=${{ env.REGISTRY }}/${{ env.REPO_LOWER }}/worker
          tags: |
            type=raw,value=latest,enable={{is_default_branch}}
            type=sha,value=latest,enable={{is_default_branch}}
          flavor: |
            latest=auto
      - name: Retag action for solr
        if: ${{ inputs.solr }}
        uses: docker/metadata-action@v4.1.1
        with:
          images: |
            name=${{ env.REGISTRY }}/${{ env.REPO_LOWER }}/solr
          tags: |
            type=raw,value=latest,enable={{is_default_branch}}
            type=sha,value=latest,enable={{is_default_branch}}
          flavor: |
            latest=auto
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push web
        uses: docker/build-push-action@v3
        with:
          context: .
          platforms: ${{ inputs.platforms }}
          target: ${{ inputs.target }}
          cache-from: |
            ${{ env.REGISTRY }}/${{ env.REPO_LOWER }}:${{ env.TAG }}
          push: ${{ github.ref == 'refs/heads/main' }}
          tags: ${{ steps.meta.outputs.tags }}
      - name: Build and push worker
        if: ${{ inputs.worker }}
        uses: docker/build-push-action@v3
        with:
          context: .
          platforms: ${{ inputs.platforms }}
          target: ${{ inputs.workerTarget }}
          cache-from: |
            ${{ env.REGISTRY }}/${{ env.REPO_LOWER }}/worker:${{ env.TAG }}
          push: ${{ github.ref == 'refs/heads/main' }}
          tags: ${{ steps.meta.outputs.tags }}
      - name: Build and push solr
        if: ${{ inputs.solr }}
        uses: docker/build-push-action@v3
        with:
          context: solr
          platforms: ${{ inputs.platforms }}
          cache-from: |
            ${{ env.REGISTRY }}/${{ env.REPO_LOWER }}/solr:${{ env.TAG }}
          push: ${{ github.ref == 'refs/heads/main' }}
          tags: ${{ steps.meta.outputs.tags }}
