name: "Build Docker Images"
on:
  workflow_call:
    inputs:
      app_name:
        type: string
      baseTarget:
        required: false
        type: string
      image_name:
        type: string
        description: "Docker image name part. Fills in ghcr.io/IMAGE_NAME. Typically this is the `repo_name`, but in some projects it might be `repo_name/sub_name`"
      image_registry:
        type: string
        description: "Docker image registry part. Defaults to ghcr.io"
      platforms:
        default: "linux/amd64,linux/arm64"
        type: string
      registry_user:
        type: string
      subdir:
        default: '.'
        type: string
      solrTarget:
        required: false
        type: string
      tag:
        required: false
        type: string
      webTarget:
        required: false
        type: string
      workerTarget:
        required: false
        type: string

env:
  REGISTRY: ${{ inputs.image_registry || 'ghcr.io' }}

jobs:
  build:
    runs-on: self-hosted
    steps:
      - id: setup
        name: Setup
        uses: glass-canvas/actions/setup-env@main
        with:
          tag: ${{ inputs.tag }}
          image_name: ${{ inputs.image_name }}
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          submodules: true
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Context for Buildx
        run: docker context create builders
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        id: builder
        with:
          version: latest
          endpoint: builders
      - name: Append ARM buildx builder
        uses: baschny/append-buildx-action@v1
        with:
          builder: ${{ steps.builder.outputs.name }}
          endpoint: "ssh://ec2-user@18.246.29.3"
          ssh_private_key: ${{ secrets.SSH_BESTIE_BUILDER_PRIVATE_KEY }}
      - name: Pull web from cache to speed up build
        if: ${{ inputs.webTarget != '' }}
        run: >-
          cd ${{ inputs.subdir }};
          touch .env.development;
          touch .env;
          TAG=latest docker-compose pull web || true
      - name: Pull base from cache to speed up build
        if: ${{ inputs.baseTarget != '' }}
        run: >-
          cd ${{ inputs.subdir }};
          touch .env.development;
          touch .env;
          TAG=latest docker-compose pull base || true
      - name: Pull worker from cache to speed up build
        if: ${{ inputs.workerTarget != '' }}
        run: >-
          cd ${{ inputs.subdir }};
          touch .env.development;
          touch .env;
          TAG=latest docker-compose pull worker || true
      - name: Pull solr from cache to speed up build
        if: ${{ inputs.solrTarget != '' }}
        run: >-
          cd ${{ inputs.subdir }};
          touch .env.development;
          touch .env;
          TAG=latest docker-compose pull solr || true
      - name: Retag action for base
        if: ${{ inputs.baseTarget != '' }}
        id: meta-base
        uses: docker/metadata-action@v4.1.1
        with:
          images: |
            name=${{ env.REGISTRY }}/${{ env.REPO_LOWER }}/base
          tags: |
            type=raw,value=latest,enable={{is_default_branch}}
      - name: Retag action for web
        if: ${{ inputs.webTarget != '' }}
        id: meta-web
        uses: docker/metadata-action@v4.1.1
        with:
          images: |
            name=${{ env.REGISTRY }}/${{ env.REPO_LOWER }}
          tags: |
            type=raw,value=latest,enable={{is_default_branch}}
      - name: Retag action for worker
        if: ${{ inputs.workerTarget != '' }}
        id: meta-worker
        uses: docker/metadata-action@v4.1.1
        with:
          images: |
            name=${{ env.REGISTRY }}/${{ env.REPO_LOWER }}/worker
          tags: |
            type=raw,value=latest,enable={{is_default_branch}}
      - name: Retag action for solr
        if: ${{ inputs.solrTarget != '' }}
        id: meta-solr
        uses: docker/metadata-action@v4.1.1
        with:
          images: |
            name=${{ env.REGISTRY }}/${{ env.REPO_LOWER }}/solr
          tags: |
            type=raw,value=latest,enable={{is_default_branch}}
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ inputs.registry_user || github.actor }}
          password: ${{ secrets.REGISTRY_PASSWORD || secrets.GITHUB_TOKEN }}
      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3
        if: ${{ github.event_name == 'workflow_dispatch' && inputs.debug_enabled }}
        with:
          limit-access-to-actor: true
      - name: Build and push base
        if: ${{ inputs.baseTarget != '' }}
        uses: docker/build-push-action@v3
        with:
          build-args: |
            "APP_PATH=${{ inputs.subdir }}"
            "APP_NAME=${{ inputs.app_name }}"
            "BRANCH=${{ env.TAG }}"
            "DEPLOY_KEY=${{ secrets.DEPLOY_KEY }}"
            "GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }}"
          cache-from: type=registry,ref=${{ env.REGISTRY }}/${{ env.REPO_LOWER }}/base:${{ env.TAG }}
          context: .
          file: ${{ inputs.subdir}}/Dockerfile
          platforms: ${{ inputs.platforms }}
          push: true
          tags: |
            ${{ steps.meta-base.outputs.tags }}
            ${{ env.REGISTRY }}/${{ env.REPO_LOWER }}/base:${{ env.TAG }}
          target: ${{ inputs.baseTarget }}
      - name: Build and push web
        if: ${{ inputs.webTarget != '' }}
        uses: docker/build-push-action@v3
        with:
          build-args: |
            "APP_PATH=${{ inputs.subdir }}"
            "APP_NAME=${{ inputs.app_name }}"
            "BRANCH=${{ env.TAG }}"
            "DEPLOY_KEY=${{ secrets.DEPLOY_KEY }}"
            "GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }}"
          cache-from: type=registry,ref=${{ env.REGISTRY }}/${{ env.REPO_LOWER }}:${{ env.TAG }}
          context: .
          file: ${{ inputs.subdir}}/Dockerfile
          platforms: ${{ inputs.platforms }}
          push: true
          tags: |
            ${{ steps.meta-web.outputs.tags }}
            ${{ env.REGISTRY }}/${{ env.REPO_LOWER }}:${{ env.TAG }}
          target: ${{ inputs.webTarget }}
      - name: Build and push worker
        if: ${{ inputs.workerTarget != '' }}
        uses: docker/build-push-action@v3
        with:
          build-args: |
            APP_PATH=${{ inputs.subdir }}
            APP_NAME=${{ inputs.app_name }}
            BRANCH=${{ env.TAG }}
            "DEPLOY_KEY=${{ secrets.DEPLOY_KEY }}"
            "GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }}"
          cache-from: type=registry,ref=${{ env.REGISTRY }}/${{ env.REPO_LOWER }}/worker:${{ env.TAG }}
          context: .
          file: ${{ inputs.subdir}}/Dockerfile
          platforms: ${{ inputs.platforms }}
          push: true
          tags: |
            ${{ steps.meta-worker.outputs.tags }}
            ${{ env.REGISTRY }}/${{ env.REPO_LOWER }}/worker:${{ env.TAG }}
          target: ${{ inputs.workerTarget }}
      - name: Build and push solr
        if: ${{ inputs.solrTarget != '' }}
        uses: docker/build-push-action@v3
        with:
          cache-from: type=registry,ref=${{ env.REGISTRY }}/${{ env.REPO_LOWER }}/solr:${{ env.TAG }}
          context: .
          platforms: ${{ inputs.platforms }}
          push: true
          tags: |
            ${{ steps.meta-solr.outputs.tags }}
            ${{ env.REGISTRY }}/${{ env.REPO_LOWER }}/solr:${{ env.TAG }}
          target: ${{ inputs.solrTarget }}
