name: "Build Docker Images"
on:
  workflow_dispatch:
    inputs:
      image_name:
        type: string
        description: "Docker image name part. Fills in ghcr.io/IMAGE_NAME. Typically this is the `repo_name`, but in some projects it might be `repo_name/sub_name`"
      platforms:
        default: "linux/amd64,linux/arm64"
        type: string
      subdir:
        default: '.'
        type: string
      tag:
        required: false
        type: string
      target:
        required: false
        type: string
      worker:
        required: false
        type: boolean
      workerTarget:
        required: false
        type: string
  workflow_call:
    inputs:
      image_name:
        type: string
        description: "Docker image name part. Fills in ghcr.io/IMAGE_NAME. Typically this is the `repo_name`, but in some projects it might be `repo_name/sub_name`"
      platforms:
        default: "linux/amd64,linux/arm64"
        type: string
      subdir:
        default: '.'
        type: string
      tag:
        required: false
        type: string
      target:
        required: false
        type: string
      worker:
        required: false
        type: boolean
      workerTarget:
        required: false
        type: string

env:
  REGISTRY: ghcr.io

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - id: setup
        name: Setup
        uses: scientist-softserv/actions/setup-env@main
        with:
          tag: ${{ inputs.tag }}
          image_name: ${{ inputs.image_name }}
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          submodules: true
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Github Container Login
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Pull from cache to speed up build
        run: >-
          cd ${{ inputs.subdir }};
          touch .env.development;
          touch .env;
          TAG=latest docker-compose pull web || true
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          build-args: |
            APP_PATH=${{ inputs.subdir }}
          cache-from: |
            ${{ env.REGISTRY }}/${{ env.REPO_LOWER }}:${{ env.TAG }}
          context: .
          file: ${{ inputs.subdir}}/Dockerfile
          platforms: ${{ inputs.platforms }}
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ env.REPO_LOWER }}:${{ env.TAG }}
          target: ${{ inputs.target }}
      - name: Build and push worker
        uses: docker/build-push-action@v3
        with:
          build-args: |
            APP_PATH=${{ inputs.subdir }}
          cache-from: |
            ${{ env.REGISTRY }}/${{ env.REPO_LOWER }}:${{ env.TAG }}
          context: .
          file: ${{ inputs.subdir}}/Dockerfile
          platforms: ${{ inputs.platforms }}
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ env.REPO_LOWER }}/worker:${{ env.TAG }}
          target: ${{ inputs.workerTarget }}
        if: ${{ inputs.worker }}
