name: "Lint for Rails Projects"
on:
  workflow_dispatch:
    inputs:
      worker:
        required: false
        type: boolean
      tag:
        required: false
        type: string
  workflow_call:
    inputs:
      worker:
        required: false
        type: boolean
      tag:
        required: false
        type: string

env:
  REGISTRY: ghcr.io

jobs:
  lint:
    runs-on: self-hosted
    steps:
      - id: setup
        name: Setup
        uses: scientist-softserv/actions/setup-env@self-hosted-runner
        with:
          tag: ${{ inputs.tag }}
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          repository: ${{ github.repository }}
          path: ${{ github.event.repository.name }}
      - name: Github Container Login
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Pull image to prevent build # line 1 (line 45?): docker-compose: command not found
                                          # Error: Process completed with exit code 127.
        run: >-
          touch .env.development;
          touch .env;
          docker-compose pull web
      - name: Pull worker image to prevent build
        run: >-
          docker-compose pull worker
        if: ${{ inputs.worker }}
      - name: Run Rubocop
        run: docker-compose run web bundle exec rubocop --parallel --format progress
      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v3
        if: always() # always run even if the previous step fails
        with:
          report_paths: 'rubocop*.xml'
