name: "Retag the item on main"
on:
  workflow_dispatch:
    inputs:
      worker:
        required: false
        type: boolean
      tag:
        required: false
        type: string
  workflow_call:
    inputs:
      worker:
        required: false
        type: boolean
      tag:
        required: false
        type: string

env:
  REGISTRY: ghcr.io

jobs:
  retag:
    runs-on: self-hosted
    if: ${{ github.ref == 'refs/heads/main' }}
    steps:
      - name: Tell me what's my TAG Before
        run: >-
          echo "My env.tag is: '${{ env.TAG }}'"
          echo "My inputs.tag is '${{ inputs.tag }}'"
      - id: setup
        name: Setup
        uses: scientist-softserv/actions/setup-env@main
        with:
          tag: ${{ inputs.tag || env.TAG }}
      - name: Tell me what's my TAG After the inputs.tag override
        run: >-
          echo "Don't forget our inputs.tag is ${{ inputs.tag }}"
          echo "And now inputs.tag should override env.tag from the input in Stage 'Tell me what's my TAG Before' to ${{ env.TAG }}, which should be a different value only if their was a value in inputs.tag"
      - name: Retag web to latest
        uses: koraykoska/retag-docker-image@0.2.4
        with:
          registry: ${{ env.REGISTRY }}
          name: ${{ env.REPO_LOWER }}
          old_tag: ${{ env.TAG }}
          new_tag: latest
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Retag worker to latest
        uses: koraykoska/retag-docker-image@0.2.4
        with:
          registry: ${{ env.REGISTRY }}
          name: ${{ env.REPO_LOWER }}/worker
          old_tag: ${{ env.TAG }}
          new_tag: latest
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
        if: ${{ inputs.worker }}