name: "Retag the image on main to latest"
on:
  workflow_dispatch:
    inputs:
      worker:
        required: false
        type: boolean
      tag:
        required: false
        type: string
      solr:
        required: false
        type: string
  workflow_call:
    inputs:
      worker:
        required: false
        type: boolean
      tag:
        required: false
        type: string
      solr:
        required: false
        type: string

env:
  REGISTRY: ghcr.io

jobs:
  retag:
    runs-on: self-hosted
    if: ${{ github.ref == 'refs/heads/main' }}
    steps:
      - id: setup
        name: Setup
        uses: scientist-softserv/actions/setup-env@self-hosted-runner
        with:
          tag: ${{ inputs.tag }}
      - name: Docker Metadata action for web
        uses: docker/metadata-action@v4.1.1
        with:
          images: |
            name=${{ env.REGISTRY }}/${{ env.REPO_LOWER }}
          tags: |
            type=raw,value=latest,enable={{is_default_branch}}
          flavor: |
            latest=auto
      - name: Docker Metadata action for worker
        if: ${{ inputs.worker }}
        uses: docker/metadata-action@v4.1.1
        with:
          images: |
            name=${{ env.REGISTRY }}/${{ env.REPO_LOWER }}/worker
          tags: |
            type=raw,value=latest,enable={{is_default_branch}}
          flavor: |
            latest=auto
      - name: Docker Metadata action for solr
        if: ${{ inputs.solr }}
        uses: docker/metadata-action@v4.1.1
        with:
          images: |
            name=${{ env.REGISTRY }}/${{ env.REPO_LOWER }}/solr
          tags: |
            type=raw,value=latest,enable={{is_default_branch}}
          flavor: |
            latest=auto